language: php

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.3
      dist: precise

before_install:
  - composer selfupdate

script:
  - composer install
  - npm install
  - grunt standards
