language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 7.0

before_install:
  - composer selfupdate

script:
  - composer install
  - npm install
  - grunt standards
